# -*- coding: utf-8 -*-
"""Parkinsons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izS80F80sNRvtY4FPOLlW8jFdgC5zPlW
"""

import numpy as np
import pandas as pd
import os, sys
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from xgboost import XGBClassifier

#read data
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/parkinsons.data")

df.head(5)

#get features and labels
features = df.loc[:,df.columns!='status'].values[:,1:]
labels = df.loc[:,'status'].values

#get count of labels; 0 and 1
print(labels[labels==1].shape[0], labels[labels==0].shape[0])

#scale the features to between -1 and 1
scaler = MinMaxScaler((-1,1))
x=scaler.fit_transform(features)
y=labels

#split datasets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,  random_state=7)

"""Train the model"""

model = XGBClassifier()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print(accuracy_score(y_test, y_pred)*100)